### ISSUE TITLE
Beta version to-do list

### ISSUE THREAD

**Issue by akainic** [department-of-veterans-affairs/healthcare-application#37]
#### Navigation
- [ ] Continue button component that moves from one section of questions to the next
- [ ] Map continue-button navigation to urls (moving through sections of questions should update url)
- [ ] Map continue-button navigation to tabs (moving through panels should update selected tab)
- [ ] Store completeness state of sections of questions and disable continue button if current section is not complete
- [ ] Optional: back button component
#### Form elements
- [ ] Anchor tag component
- [ ] Non-errorable text input component
- [ ] Errorable checkbox component
- [ ] Non-errorable checkbox component
- [ ] Non-errorable radio component
- [ ] Errorable select component
- [ ] Non-errorable select component
- [ ] Submit button component (to replace final continue button)
#### Questions
- [ ] Question components for each section
- [ ] Adding/removing multiple children for each applicable question functional
- [ ] Validations for all required questions are set
#### Form
- [ ] All panels have components
- [ ] All sections have components (and are included in appropriate panel with correct props)
- [ ] State is initialized for entire app
#### XML
- [ ] Parse questions
- [ ] Submit
#### Appearance
- [ ] Style tab navigation/progress bar
- [ ] Make sure grid is applied correctly and questions are spaced out
- [ ] Make sure validation styles are applied correctly to all input types (pay extra attention to checkboxes, radio buttons and multi-select inputs (e.g., dates))
- [ ] Responsive (especially navigation)
#### General improvements
- [ ] Organizing component files into meaningful directories
- [ ] Check that remaining TODOs in code are addressed
- [ ] Check code coverage

### Week 1 to-do
(move items here when total list finalized)

### Week 2 to-do
(move items here when total list finalized)
